schema_version: 1
id: bass_v1
name: HVLIEN Bass Session v1

voice:
  script: profiles/hvlien/specs/voice/scripts/bass_template_build.v1.yaml
  abi: profiles/hvlien/specs/voice/abi/hvlien_macro_abi.v1.yaml
  macro_ocr: true
  macro_region: rack.macros

racks:
  manifest: profiles/hvlien/specs/library/racks/rack_pack_manifest.v1.json
  macro_region: rack.macros

automation:
  anchors_pack: specs/automation/anchors/<pack_id>
  regions: tools/automation/swift-cli/config/regions.v1.json
  watchdog_ms: 30000

notes:
  - Replace <pack_id> in anchors_pack with your actual anchor pack directory.
